version: '2'

services:
  flask:
    restart: always
    container_name: flask
    build: .
    volumes:
      - ./:/deploy
    ports:
      - 8080:8080
  nginx:
    restart: always
    image: nginx:1.17
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./static:/var/www/static
      - ./ssl:/ssl
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - flask
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
